<?php
namespace Empari\Geo\Database\Seeders;

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('countries')->delete();

        \Empari\Geo\Models\Country::insert(array(
            array('id' => 132, 'name' => ucwords(strtolower('AFEGANISTAO'))),
            array('id' => 175, 'name' => ucwords(strtolower('ALBANIA'))),
            array('id' => 230, 'name' => ucwords(strtolower('ALEMANHA'))),
            array('id' => 310, 'name' => ucwords(strtolower('BURKINA FASO'))),
            array('id' => 370, 'name' => ucwords(strtolower('ANDORRA'))),
            array('id' => 400, 'name' => ucwords(strtolower('ANGOLA'))),
            array('id' => 418, 'name' => ucwords(strtolower('ANGUILLA'))),
            array('id' => 434, 'name' => ucwords(strtolower('ANTIGUA E BARBUDA'))),
            array('id' => 477, 'name' => ucwords(strtolower('ANTILHAS HOLANDESAS'))),
            array('id' => 531, 'name' => ucwords(strtolower('ARABIA SAUDITA'))),
            array('id' => 590, 'name' => ucwords(strtolower('ARGELIA'))),
            array('id' => 639, 'name' => ucwords(strtolower('ARGENTINA'))),
            array('id' => 647, 'name' => ucwords(strtolower('ARMENIA'))),
            array('id' => 655, 'name' => ucwords(strtolower('ARUBA'))),
            array('id' => 698, 'name' => ucwords(strtolower('AUSTRALIA'))),
            array('id' => 728, 'name' => ucwords(strtolower('AUSTRIA'))),
            array('id' => 736, 'name' => ucwords(strtolower('AZERBAIJAO'))),
            array('id' => 779, 'name' => ucwords(strtolower('ILHAS BAHAMAS'))),
            array('id' => 809, 'name' => ucwords(strtolower('ILHAS BAHREIN'))),
            array('id' => 817, 'name' => ucwords(strtolower('BANGLADESH'))),
            array('id' => 833, 'name' => ucwords(strtolower('BARBADOS'))),
            array('id' => 850, 'name' => ucwords(strtolower('BELARUS'))),
            array('id' => 876, 'name' => ucwords(strtolower('BELGICA'))),
            array('id' => 884, 'name' => ucwords(strtolower('BELIZE'))),
            array('id' => 906, 'name' => ucwords(strtolower('BERMUDAS'))),
            array('id' => 930, 'name' => ucwords(strtolower('MIANMAR'))),
            array('id' => 973, 'name' => ucwords(strtolower('BOLIVIA'))),
            array('id' => 981, 'name' => ucwords(strtolower('BOSNIA HERZEGOVINA'))),
            array('id' => 1015, 'name' => ucwords(strtolower('BOTSUANA'))),
            array('id' => 1058, 'name' => ucwords(strtolower('BRASIL'))),
            array('id' => 1082, 'name' => ucwords(strtolower('BRUNEI'))),
            array('id' => 1112, 'name' => ucwords(strtolower('BULGARIA'))),
            array('id' => 1155, 'name' => ucwords(strtolower('BURUNDI'))),
            array('id' => 1198, 'name' => ucwords(strtolower('BUTAO'))),
            array('id' => 1279, 'name' => ucwords(strtolower('CABO VERDE'))),
            array('id' => 1376, 'name' => ucwords(strtolower('ILHAS CAYMAN'))),
            array('id' => 1414, 'name' => ucwords(strtolower('CAMBOJA'))),
            array('id' => 1457, 'name' => ucwords(strtolower('CAMAROES'))),
            array('id' => 1490, 'name' => ucwords(strtolower('CANADA'))),
            array('id' => 1504, 'name' => ucwords(strtolower('ILHAS DO CANAL'))),
            array('id' => 1511, 'name' => ucwords(strtolower('ILHAS CANARIAS'))),
            array('id' => 1538, 'name' => ucwords(strtolower('CAZAQUISTAO'))),
            array('id' => 1546, 'name' => ucwords(strtolower('CATAR'))),
            array('id' => 1589, 'name' => ucwords(strtolower('CHILE'))),
            array('id' => 1600, 'name' => ucwords(strtolower('CHINA'))),
            array('id' => 1619, 'name' => ucwords(strtolower('FORMOSA'))),
            array('id' => 1635, 'name' => ucwords(strtolower('CHIPRE'))),
            array('id' => 1651, 'name' => ucwords(strtolower('ILHAS COCOS'))),
            array('id' => 1694, 'name' => ucwords(strtolower('COLOMBIA'))),
            array('id' => 1732, 'name' => ucwords(strtolower('ILHAS COMORES'))),
            array('id' => 1775, 'name' => ucwords(strtolower('REPUBLICA DO CONGO'))),
            array('id' => 1830, 'name' => ucwords(strtolower('ILHAS COOK'))),
            array('id' => 1872, 'name' => ucwords(strtolower('REP POP DEMOCRATICA DA COREIA'))),
            array('id' => 1902, 'name' => ucwords(strtolower('COREIA'))),
            array('id' => 1937, 'name' => ucwords(strtolower('COSTA DO MARFIM'))),
            array('id' => 1953, 'name' => ucwords(strtolower('CROACIA'))),
            array('id' => 1961, 'name' => ucwords(strtolower('COSTA RICA'))),
            array('id' => 1988, 'name' => ucwords(strtolower('COVEITE'))),
            array('id' => 1996, 'name' => ucwords(strtolower('CUBA'))),
            array('id' => 2291, 'name' => ucwords(strtolower('BENIN'))),
            array('id' => 2321, 'name' => ucwords(strtolower('DINAMARCA'))),
            array('id' => 2356, 'name' => ucwords(strtolower('ILHA DOMINICA'))),
            array('id' => 2399, 'name' => ucwords(strtolower('EQUADOR'))),
            array('id' => 2402, 'name' => ucwords(strtolower('EGITO'))),
            array('id' => 2437, 'name' => ucwords(strtolower('ERITREIA'))),
            array('id' => 2445, 'name' => ucwords(strtolower('EMIRADOS ARABES UNIDOS'))),
            array('id' => 2453, 'name' => ucwords(strtolower('ESPANHA'))),
            array('id' => 2461, 'name' => ucwords(strtolower('ESLOVENIA'))),
            array('id' => 2470, 'name' => ucwords(strtolower('ESLOVACA'))),
            array('id' => 2496, 'name' => ucwords(strtolower('ESTADOS UNIDOS'))),
            array('id' => 2518, 'name' => ucwords(strtolower('ESTONIA'))),
            array('id' => 2534, 'name' => ucwords(strtolower('ETIOPIA'))),
            array('id' => 2550, 'name' => ucwords(strtolower('FALKLAND'))),
            array('id' => 2593, 'name' => ucwords(strtolower('ILHAS FEROE'))),
            array('id' => 2674, 'name' => ucwords(strtolower('FILIPINAS'))),
            array('id' => 2712, 'name' => ucwords(strtolower('FINLANDIA'))),
            array('id' => 2755, 'name' => ucwords(strtolower('FRANCA'))),
            array('id' => 2810, 'name' => ucwords(strtolower('GABAO'))),
            array('id' => 2852, 'name' => ucwords(strtolower('GAMBIA'))),
            array('id' => 2895, 'name' => ucwords(strtolower('GANA'))),
            array('id' => 2917, 'name' => ucwords(strtolower('GEORGIA'))),
            array('id' => 2933, 'name' => ucwords(strtolower('GIBRALTAR'))),
            array('id' => 2976, 'name' => ucwords(strtolower('GRANADA'))),
            array('id' => 3018, 'name' => ucwords(strtolower('GRECIA'))),
            array('id' => 3050, 'name' => ucwords(strtolower('GROENLANDIA'))),
            array('id' => 3093, 'name' => ucwords(strtolower('GUADALUPE'))),
            array('id' => 3131, 'name' => ucwords(strtolower('GUAM'))),
            array('id' => 3174, 'name' => ucwords(strtolower('GUATEMALA'))),
            array('id' => 3255, 'name' => ucwords(strtolower('GUIANA FRANCESA'))),
            array('id' => 3298, 'name' => ucwords(strtolower('GUINE'))),
            array('id' => 3310, 'name' => ucwords(strtolower('GUINE EQUATORIAL'))),
            array('id' => 3344, 'name' => ucwords(strtolower('GUINE BISSAU'))),
            array('id' => 3379, 'name' => ucwords(strtolower('GUIANA'))),
            array('id' => 3417, 'name' => ucwords(strtolower('HAITI'))),
            array('id' => 3450, 'name' => ucwords(strtolower('HONDURAS'))),
            array('id' => 3514, 'name' => ucwords(strtolower('REGIAO ADM ESPECIAL HONG KONG'))),
            array('id' => 3557, 'name' => ucwords(strtolower('HUNGRIA'))),
            array('id' => 3573, 'name' => ucwords(strtolower('IEMEN'))),
            array('id' => 3595, 'name' => ucwords(strtolower('ILHAS MAN'))),
            array('id' => 3611, 'name' => ucwords(strtolower('INDIA'))),
            array('id' => 3654, 'name' => ucwords(strtolower('INDONESIA'))),
            array('id' => 3697, 'name' => ucwords(strtolower('IRAQUE'))),
            array('id' => 3727, 'name' => ucwords(strtolower('REPUBLICA ISLAMICA DO IRA'))),
            array('id' => 3751, 'name' => ucwords(strtolower('IRLANDA'))),
            array('id' => 3794, 'name' => ucwords(strtolower('ISLANDIA'))),
            array('id' => 3832, 'name' => ucwords(strtolower('ISRAEL'))),
            array('id' => 3867, 'name' => ucwords(strtolower('ITALIA'))),
            array('id' => 3883, 'name' => ucwords(strtolower('IUGOSLAVIA'))),
            array('id' => 3913, 'name' => ucwords(strtolower('JAMAICA'))),
            array('id' => 3964, 'name' => ucwords(strtolower('ILHAS JOHNSTON'))),
            array('id' => 3999, 'name' => ucwords(strtolower('JAPAO'))),
            array('id' => 4030, 'name' => ucwords(strtolower('JORDANIA'))),
            array('id' => 4111, 'name' => ucwords(strtolower('KIRIBATI'))),
            array('id' => 4200, 'name' => ucwords(strtolower('REP POP DEMOCRATICA DO LAOS'))),
            array('id' => 4235, 'name' => ucwords(strtolower('LEBUAN'))),
            array('id' => 4260, 'name' => ucwords(strtolower('LESOTO'))),
            array('id' => 4278, 'name' => ucwords(strtolower('LETONIA'))),
            array('id' => 4316, 'name' => ucwords(strtolower('LIBANO'))),
            array('id' => 4340, 'name' => ucwords(strtolower('LIBERIA'))),
            array('id' => 4383, 'name' => ucwords(strtolower('LIBIA'))),
            array('id' => 4405, 'name' => ucwords(strtolower('LIECHTENSTEIN'))),
            array('id' => 4421, 'name' => ucwords(strtolower('LITUANIA'))),
            array('id' => 4456, 'name' => ucwords(strtolower('LUXEMBURGO'))),
            array('id' => 4472, 'name' => ucwords(strtolower('MACAU'))),
            array('id' => 4499, 'name' => ucwords(strtolower('MACEDONIA'))),
            array('id' => 4502, 'name' => ucwords(strtolower('MADAGASCAR'))),
            array('id' => 4525, 'name' => ucwords(strtolower('ILHA DA MADEIRA'))),
            array('id' => 4553, 'name' => ucwords(strtolower('MALASIA'))),
            array('id' => 4588, 'name' => ucwords(strtolower('MALAVI'))),
            array('id' => 4618, 'name' => ucwords(strtolower('MALDIVAS'))),
            array('id' => 4642, 'name' => ucwords(strtolower('MALI'))),
            array('id' => 4677, 'name' => ucwords(strtolower('MALTA'))),
            array('id' => 4723, 'name' => ucwords(strtolower('MARIANAS DO NORTE'))),
            array('id' => 4740, 'name' => ucwords(strtolower('MARROCOS'))),
            array('id' => 4766, 'name' => ucwords(strtolower('ILHAS MARSHALL'))),
            array('id' => 4774, 'name' => ucwords(strtolower('MARTINICA'))),
            array('id' => 4855, 'name' => ucwords(strtolower('MAURICIO'))),
            array('id' => 4880, 'name' => ucwords(strtolower('MAURITANIA'))),
            array('id' => 4901, 'name' => ucwords(strtolower('ILHAS MIDWAY'))),
            array('id' => 4936, 'name' => ucwords(strtolower('MEXICO'))),
            array('id' => 4944, 'name' => ucwords(strtolower('MOLDAVIA'))),
            array('id' => 4952, 'name' => ucwords(strtolower('MONACO'))),
            array('id' => 4979, 'name' => ucwords(strtolower('MONGOLIA'))),
            array('id' => 4995, 'name' => ucwords(strtolower('MICRONESIA'))),
            array('id' => 5010, 'name' => ucwords(strtolower('ILHAS MONTSERRAT'))),
            array('id' => 5053, 'name' => ucwords(strtolower('MOCAMBIQUE'))),
            array('id' => 5070, 'name' => ucwords(strtolower('NAMIBIA'))),
            array('id' => 5088, 'name' => ucwords(strtolower('NAURU'))),
            array('id' => 5118, 'name' => ucwords(strtolower('ILHA CHRISTMAS'))),
            array('id' => 5177, 'name' => ucwords(strtolower('NEPAL'))),
            array('id' => 5215, 'name' => ucwords(strtolower('NICARAGUA'))),
            array('id' => 5258, 'name' => ucwords(strtolower('NIGER'))),
            array('id' => 5282, 'name' => ucwords(strtolower('NIGERIA'))),
            array('id' => 5312, 'name' => ucwords(strtolower('ILHA NIUE'))),
            array('id' => 5355, 'name' => ucwords(strtolower('ILHA NORFOLK'))),
            array('id' => 5380, 'name' => ucwords(strtolower('NORUEGA'))),
            array('id' => 5428, 'name' => ucwords(strtolower('NOVA CALEDONIA'))),
            array('id' => 5452, 'name' => ucwords(strtolower('PAPUA NOVA GUINE'))),
            array('id' => 5487, 'name' => ucwords(strtolower('NOVA ZELANDIA'))),
            array('id' => 5517, 'name' => ucwords(strtolower('VANUATU'))),
            array('id' => 5568, 'name' => ucwords(strtolower('OMA'))),
            array('id' => 5738, 'name' => ucwords(strtolower('HOLANDA'))),
            array('id' => 5754, 'name' => ucwords(strtolower('PALAU'))),
            array('id' => 5762, 'name' => ucwords(strtolower('PAQUISTAO'))),
            array('id' => 5800, 'name' => ucwords(strtolower('PANAMA'))),
            array('id' => 5860, 'name' => ucwords(strtolower('PARAGUAI'))),
            array('id' => 5894, 'name' => ucwords(strtolower('PERU'))),
            array('id' => 5932, 'name' => ucwords(strtolower('ILHA PITCAIRN'))),
            array('id' => 5991, 'name' => ucwords(strtolower('POLINESIA FRANCESA'))),
            array('id' => 6033, 'name' => ucwords(strtolower('POLONIA'))),
            array('id' => 6076, 'name' => ucwords(strtolower('PORTUGAL'))),
            array('id' => 6114, 'name' => ucwords(strtolower('PORTO RICO'))),
            array('id' => 6238, 'name' => ucwords(strtolower('QUENIA'))),
            array('id' => 6254, 'name' => ucwords(strtolower('QUIRGUIZ'))),
            array('id' => 6289, 'name' => ucwords(strtolower('ESCOCIA'))),
            array('id' => 6408, 'name' => ucwords(strtolower('REPUBLICA CENTRO AFRICANA'))),
            array('id' => 6475, 'name' => ucwords(strtolower('REPUBLICA DOMINICANA'))),
            array('id' => 6602, 'name' => ucwords(strtolower('ILHA REUNIAO'))),
            array('id' => 6653, 'name' => ucwords(strtolower('ZIMBABUE'))),
            array('id' => 6700, 'name' => ucwords(strtolower('ROMENIA'))),
            array('id' => 6750, 'name' => ucwords(strtolower('RUANDA'))),
            array('id' => 6769, 'name' => ucwords(strtolower('RUSSIA'))),
            array('id' => 6777, 'name' => ucwords(strtolower('ILHAS SALOMAO'))),
            array('id' => 6858, 'name' => ucwords(strtolower('SAARA OCIDENTAL'))),
            array('id' => 6874, 'name' => ucwords(strtolower('EL SALVADOR'))),
            array('id' => 6904, 'name' => ucwords(strtolower('SAMOA'))),
            array('id' => 6912, 'name' => ucwords(strtolower('SAMOA AMERICANA'))),
            array('id' => 6955, 'name' => ucwords(strtolower('SAO CRISTOVAO E NEVES'))),
            array('id' => 6971, 'name' => ucwords(strtolower('SAN MARINO'))),
            array('id' => 7005, 'name' => ucwords(strtolower('SAO PEDRO E MIQUELON'))),
            array('id' => 7056, 'name' => ucwords(strtolower('SAO VICENTE E GRANADINAS'))),
            array('id' => 7102, 'name' => ucwords(strtolower('SANTA HELENA'))),
            array('id' => 7153, 'name' => ucwords(strtolower('SANTA LUCIA'))),
            array('id' => 7200, 'name' => ucwords(strtolower('ILHAS SAO TOME E PRINCIPE'))),
            array('id' => 7285, 'name' => ucwords(strtolower('SENEGAL'))),
            array('id' => 7315, 'name' => ucwords(strtolower('SEYCHELLES'))),
            array('id' => 7358, 'name' => ucwords(strtolower('SERRA LEOA'))),
            array('id' => 7412, 'name' => ucwords(strtolower('CINGAPURA'))),
            array('id' => 7447, 'name' => ucwords(strtolower('ARABE DA SIRIA'))),
            array('id' => 7480, 'name' => ucwords(strtolower('SOMALIA'))),
            array('id' => 7501, 'name' => ucwords(strtolower('SRI LANKA'))),
            array('id' => 7544, 'name' => ucwords(strtolower('SUAZILANDIA'))),
            array('id' => 7560, 'name' => ucwords(strtolower('AFRICA DO SUL'))),
            array('id' => 7595, 'name' => ucwords(strtolower('SUDAO'))),
            array('id' => 7641, 'name' => ucwords(strtolower('SUECIA'))),
            array('id' => 7676, 'name' => ucwords(strtolower('SUICA'))),
            array('id' => 7706, 'name' => ucwords(strtolower('SURINAME'))),
            array('id' => 7722, 'name' => ucwords(strtolower('TADJIQUISTAO'))),
            array('id' => 7765, 'name' => ucwords(strtolower('TAILANDIA'))),
            array('id' => 7803, 'name' => ucwords(strtolower('TANZANIA'))),
            array('id' => 7820, 'name' => ucwords(strtolower('TERRITORIO BRITANICO OC INDICO'))),
            array('id' => 7838, 'name' => ucwords(strtolower('DJIBUTI'))),
            array('id' => 7889, 'name' => ucwords(strtolower('CHADE'))),
            array('id' => 7919, 'name' => ucwords(strtolower('REPUBLICA TCHECA'))),
            array('id' => 7951, 'name' => ucwords(strtolower('TIMOR LESTE'))),
            array('id' => 8001, 'name' => ucwords(strtolower('TOGO'))),
            array('id' => 8052, 'name' => ucwords(strtolower('ILHAS TOQUELAU'))),
            array('id' => 8109, 'name' => ucwords(strtolower('TONGA'))),
            array('id' => 8150, 'name' => ucwords(strtolower('TRINIDAD E TOBAGO'))),
            array('id' => 8206, 'name' => ucwords(strtolower('TUNISIA'))),
            array('id' => 8230, 'name' => ucwords(strtolower('ILHAS TURCAS E CAICOS'))),
            array('id' => 8249, 'name' => ucwords(strtolower('TURCOMENISTAO'))),
            array('id' => 8273, 'name' => ucwords(strtolower('TURQUIA'))),
            array('id' => 8281, 'name' => ucwords(strtolower('TUVALU'))),
            array('id' => 8311, 'name' => ucwords(strtolower('UCRANIA'))),
            array('id' => 8338, 'name' => ucwords(strtolower('UGANDA'))),
            array('id' => 8451, 'name' => ucwords(strtolower('URUGUAI'))),
            array('id' => 8478, 'name' => ucwords(strtolower('UZBEQUISTAO'))),
            array('id' => 8486, 'name' => ucwords(strtolower('ESTADO DA CIDADE DO VATICANO'))),
            array('id' => 8508, 'name' => ucwords(strtolower('VENEZUELA'))),
            array('id' => 8583, 'name' => ucwords(strtolower('VIETNA'))),
            array('id' => 8630, 'name' => ucwords(strtolower('ILHAS VIRGENS'))),
            array('id' => 8664, 'name' => ucwords(strtolower('ILHAS VIRGENS'))),
            array('id' => 8702, 'name' => ucwords(strtolower('FIJI'))),
            array('id' => 8737, 'name' => ucwords(strtolower('ILHA WAKE'))),
            array('id' => 8753, 'name' => ucwords(strtolower('ILHAS WALLIS E FUTUNA'))),
            array('id' => 8885, 'name' => ucwords(strtolower('CONGO'))),
            array('id' => 8907, 'name' => ucwords(strtolower('ZAMBIA'))),
            array('id' => 8958, 'name' => ucwords(strtolower('ZONA DO CANAL DO PANAMA'))),
        ));
    }
}